---
before:
  hooks:
    - go mod tidy
builds:
  - id: serverscom-cloud-controller-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: serverscom-cloud-controller-manager
    ldflags:
      - "-s -w -X serverscom.providerVersion={{ if not .IsSnapshot }}v{{ end }}{{ .Version }}"
dockers:
  - ids:
      - serverscom-cloud-controller-manager
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/serverscom/serverscom-cloud-controller-manager:latest"
      - "ghcr.io/serverscom/serverscom-cloud-controller-manager:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
release:
  ids: [""]
  draft: true
